import type { Metadata } from 'next';
import './globals.css';
import { NextIntlClientProvider } from 'next-intl';

import { Sarabun, Tajawal } from 'next/font/google';

export const sarabun = Sarabun({
  subsets: ['latin'],
  weight: ['400', '500', '600', '700'],
  variable: '--font-sarabun',
});

export const tajawal = Tajawal({
  subsets: ['arabic'],
  weight: ['400', '500', '700', '800'],
  variable: '--font-tajawal',
});

export const metadata: Metadata = {
  title: 'Rose App',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
  params,
}: Readonly<{
  children: React.ReactNode;
  params: Promise<{ locale: string }>;
}>) {
  const { locale } = await params;
  return (
    <html lang={locale} dir={locale === 'ar' ? 'rtl' : 'ltr'}>
      <NextIntlClientProvider>
        <body
          className={`${sarabun.variable} ${tajawal.variable} ${locale === 'ar' ? 'font-arabic' : 'font-sans'}`}
        >
          {children}
        </body>
      </NextIntlClientProvider>
    </html>
  );
}
